name: flatnotes

services:
  web:
    image: dullage/flatnotes:latest
    restart: unless-stopped
    networks:
      - router
    hostname: flatnotes
    environment:
      - FLATNOTES_AUTH_TYPE=${FLATNOTES_AUTH_TYPE}
      - FLATNOTES_USERNAME=${FLATNOTES_USERNAME}
      - FLATNOTES_PASSWORD=${FLATNOTES_PASSWORD}
      - FLATNOTES_SECRET_KEY=${FLATNOTES_SECRET_KEY}
    volumes:
      - web-data:/data

volumes:
  web-data:

networks:
  router:
    external: True
