name: vaultwarden

secrets:
  DB_USER_PWD:
    file: .secrets/db_user_pwd
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd
  DB_URL:
    file: .secrets/db_url

services:
  web:
    image: vaultwarden/server:latest-alpine
    restart: unless-stopped
    networks:
      - default
      - router
    hostname: vaultwarden
    environment:
      - DATABASE_URL_FILE=/run/secrets/DB_URL
    volumes:
      - web-data:/data/
    secrets:
      - DB_URL
    depends_on:
      - db

  db:
    image: mariadb:lts
    restart: unless-stopped
    networks:
      - default
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PWD
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD_FILE=/run/secrets/DB_USER_PWD
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - DB_ROOT_PWD
      - DB_USER_PWD

volumes:
  web-data:
  db-data:

networks:
  default:
  router:
    external: True
