name: mysql

secrets:
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd

services:
  app:
    image: mysql:lts
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    networks:
      - router
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PWD
    volumes:
      - data:/var/lib/mysql
    secrets:
      - DB_ROOT_PWD

volumes:
  data:

networks:
  router:
    external: True