name: ghost

secrets:
  DB_USER_PWD:
    file: .secrets/db_user_pwd
  DB_ROOT_PWD:
    file: .secrets/db_root_pwd

services:
  web:
    image: ghost:latest
    restart: unless-stopped
    networks:
      - default
      - router
    hostname: ghost
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=${DB_USER}
      - database__connection__password=${DB_USER_PWD}
      - database__connection__database=${DB_NAME}
      - mail__transport=SMTP
      - mail__options__host=${SMTP_HOST}
      - mail__options__port=${SMTP_PORT}
      - mail__options__auth__user=${SMTP_USER}
      - mail__options__auth__pass=${SMTP_PASS}
      - url=${URL}
    volumes:
      - web-data:/var/lib/ghost/content
    depends_on:
      - db

  db:
    image: mysql:lts
    restart: unless-stopped
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/DB_ROOT_PWD
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD_FILE=/run/secrets/DB_USER_PWD
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - DB_ROOT_PWD
      - DB_USER_PWD

volumes:
  web-data:
  db-data:

networks:
  default:
  router:
    external: True
