name: uptimekuma

services:
  web:
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    networks:
      - router
    hostname: uptime-kuma
    volumes:
      - web-data:/app/data

volumes:
  web-data:

networks:
  router:
    external: True