name: dashy

services:
  web:
    image:  lissy93/dashy:latest
    restart: unless-stopped
    networks:
      - router
    hostname: dashy
    volumes:
      - web-data:/app/user-data

volumes:
  web-data:

networks:
  router:
    external: True